[package]
name = "basic-blockchain-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.33"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
sha2 = "0.10.8"
